---
- name: vm disk demo
  hosts: localhost
  become: false
  gather_facts: false
  collections:
    - community.vmware
  tasks:
    - name: expand disk in vm
      vmware_guest_disk:
        hostname: "172.16.51.50"
        username: "qdsentpteam@vsphere.local"
        password: "QDSP@ssw0rd"
        validate_certs: "false"
        datacenter: "QDS-Infra-DC"
        name: "Ansible Manage Node Linux"
        disk:
          - state: absent
            scsi_controller: "3"
            unit_number: "3"
